name: '[Push] Next'

on:
  push:
    branches:
      - next

concurrency: push_next

permissions:
  packages: write
  contents: read

jobs:
  tag:
    name: "Tag"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      release_type: ${{ steps.tag_version.outputs.release_type }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: next
          append_to_pre_release_tag: rc

  release:
    name: "Release ${{ needs.tag.outputs.new_tag }}"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - tag
    steps:
      - name: Create a release-candidate
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag.outputs.new_tag }}
          name: Release ${{ needs.tag.outputs.new_tag }}
          body: ${{ needs.tag.outputs.changelog }}
          prerelease: true
          draft: false


